apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura-deployment
  labels:
    app: conversao-temperatura
spec:
  replicas: 3
  selector:
    matchLabels:
      app: conversao-temperatura
  template:
    metadata:
      labels:
        app: conversao-temperatura
    spec:
      containers:
      - name: conversao-temperatura
        image: localhost:5000/kubedev/conversao-temperatura:1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura-service
spec:
  type: NodePort
  selector:
    app: conversao-temperatura
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30010