apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura-deployment
  namespace: default
  labels:
    app: conversao-temperatura
spec:
  replicas: 3
  selector:
    matchLabels:
      app: conversao-temperatura
  template:
    metadata:
      labels:
        app: conversao-temperatura
    spec:
      containers:
      - name: conversao-temperatura
        image: lucasfusinato/conversao-temperatura:1.0
        ports:
        - containerPort: 8080