apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura-service
spec:
  type: NodePort
  selector:
    app: conversao-temperatura
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30010